name: Build AnkiDroid

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Rename APK
      run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/AnkiDroid2.apk
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: AnkiDroid2-APK
        path: app/build/outputs/apk/release/AnkiDroid2.apk
